spring:
  application:
    name: price-api
server:
  port: 8082
security:
  oauth2:
    resource:
      jwt:
        key-uri: http://10.33.72.18:8090/oauth/token_key
    client:
      client-id: priceService
      client-secret: 123456